sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - env: TOX_ENV=py27
      python: 2.7
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6
    - env: TOX_ENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_ENV=lint
      python: 3.6
install:
  - pip install -U tox tox-travis
script: travis_retry tox -e $TOX_ENV
after_success:
  - codecov
